---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.2.1

platforms:
- name: windows-2012R2
  driver_config:
    box: mwrock/Windows2012R2

suites:
  - name: default
    run_list:
      - recipe[shellout-experimental::default]
